Notification screen
afras21/RN_LLOYD pull request #15
Opened 2022-04-26 04:45 UTC by Harikarthyk

2022-04-26 16:26 UTC, Harikarthyk commented
<img width="251" alt="Screenshot 2022-04-26 at 9 54 53 PM" src="https://user-images.githubusercontent.com/54505967/165347570-570fc78f-a43d-4b45-b0c5-242c3dd9001b.png">
<img width="251" alt="Screenshot 2022-04-26 at 9 54 58 PM" src="https://user-images.githubusercontent.com/54505967/165347605-4809217a-5ec9-4260-89cb-555542fdf607.png">

2022-04-27 16:40 UTC, afras21 requested changes

2022-04-27 16:40 UTC, afras21 commented on src/components/notification/Notification.js
> +    if(str.length >= 32){
Use  NoOfLines={2} props in <Text/> component instead of taking substring

2022-04-27 16:40 UTC, afras21 commented on src/screens/TransactionScreen.js
> +                        +$5.00
why hardcoded ?

2022-04-27 17:54 UTC, merged